version: '3.8'

services:
  web:
    build: .
    ports:
      - "8080:80"
    volumes:
      - .:/var/www/html
    environment:
      - MYSQL_HOST=mysql
      - MYSQL_USER=codeigniter
      - MYSQL_PASSWORD=secret
      - MYSQL_DATABASE=codeigniter
    depends_on:
      - mysql

  mysql:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: codeigniter
      MYSQL_USER: codeigniter
      MYSQL_PASSWORD: secret
    volumes:
      - mysql_data_bengkel:/var/lib/mysql

volumes:
  mysql_data_bengkel:
